GNU nano 7.2                                                               docker-compose.yml                                                                        version: '3'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/moviedb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=wheogml12!
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=wheogml12!
      - MYSQL_DATABASE=moviedb
    volumes:
      - ./mysql-data-docker:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data: